// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf_j2XiPjhRRxjTMAXVIUy0ywzSerRLWE',
    appId: '1:91081509122:web:1aa6e51cbb7dea71051a1b',
    messagingSenderId: '91081509122',
    projectId: 'chatapp-6e47a',
    authDomain: 'chatapp-6e47a.firebaseapp.com',
    storageBucket: 'chatapp-6e47a.appspot.com',
    measurementId: 'G-H3H2HQL9LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67VhLKLezQBxCn9SC_zhgAv3VQr6VGsk',
    appId: '1:91081509122:android:a8433062f0dc6634051a1b',
    messagingSenderId: '91081509122',
    projectId: 'chatapp-6e47a',
    storageBucket: 'chatapp-6e47a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIMh_3vDDN1r4rXDxNMBtWL0AP177DgP0',
    appId: '1:91081509122:ios:81dfa38025ba63cb051a1b',
    messagingSenderId: '91081509122',
    projectId: 'chatapp-6e47a',
    storageBucket: 'chatapp-6e47a.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIMh_3vDDN1r4rXDxNMBtWL0AP177DgP0',
    appId: '1:91081509122:ios:81dfa38025ba63cb051a1b',
    messagingSenderId: '91081509122',
    projectId: 'chatapp-6e47a',
    storageBucket: 'chatapp-6e47a.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf_j2XiPjhRRxjTMAXVIUy0ywzSerRLWE',
    appId: '1:91081509122:web:238ed1a2b7f8fa72051a1b',
    messagingSenderId: '91081509122',
    projectId: 'chatapp-6e47a',
    authDomain: 'chatapp-6e47a.firebaseapp.com',
    storageBucket: 'chatapp-6e47a.appspot.com',
    measurementId: 'G-NNP8V3NH77',
  );
}
